# Generated by Django 4.1.4 on 2023-05-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_alter_animal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.TextField(default=None, null=True),
        ),
    ]
