version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    command: gunicorn API.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=ih0ax7@mi)fm600%o_7c_dduqwkolrn-goaw)t1ul5ko(8ofm#
      - DB_NAME=proddb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=proddb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
  nginx:
    build: ./nginx
    ports: 
      - 1337:80
    depends_on:
      - app

volumes:
  postgres_data:



