# Generated by Django 4.1.4 on 2022-12-25 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='id',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
