name: Django Automated Test Rerun

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-test-container-job:
    runs-on: ubuntu-latest
    env:
      # Workflow level environment variables
      # Varaible Context Github action: https://docs.github.com/en/actions/learn-github-actions/contexts#vars-context
      # Secret Context Github action:: https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context
      SECRET_KEY: ${{vars.SECRET_KEY}}
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASSWORD: changeme
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      LOCAL_ALLOWED_HOST: 192.158.0.31
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: us-east-2
      AWS_STORAGE_BUCKET_NAME: petappfile
    container: python:3.10-bookworm
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{env.DB_PASSWORD}}
          POSTGRES_USER: ${{env.DB_USER}}
          POSTGRES_DB: ${{env.DB_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Database Migration
        run: |
          python3 -u app/manage.py migrate
      - name: Animal Model Test
        run: |
          python3 app/manage.py test app/animal/tests
