name: Django Automated Test Rerun

env:
  # Workflow level environment variables
  SECRET_KEY: ih0ax7@mi)fm600%o_7c_dduqwkolrn-goaw)t1ul5ko(8ofm#
  DB_NAME: devdb
  DB_USER: devuser
  DB_PASSWORD: changeme
  DB_HOST: 127.0.0.1 # same name of image host
  DB_PORT: 5432 # will map later on
  LOCAL_ALLOWED_HOST: 192.158.0.31
  AWS_ACCESS_KEY_ID: AKIAW6YLJIVHB3RCNIEO
  AWS_SECRET_ACCESS_KEY: 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
  AWS_DEFAULT_REGION: us-east-2
  AWS_STORAGE_BUCKET_NAME: petappfile

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-test-container-job:
    runs-on: ubuntu-latest
    container: python:3.10-bookworm
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_USER: $DB_USER
          POSTGRES_DB: $DB_NAME
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Database Migration
        run: |
          python3 app/manage.py migrate
      
      # TODO: fix the testing folder here with how we do database setup
      # - name: Animal Model Test
      #   run: |
      #     python3 app/manage.py test app/animal/tests
