name: Django Automated Test Rerun

env:
  SECRET_KEY: ih0ax7@mi)fm600%o_7c_dduqwkolrn-goaw)t1ul5ko(8ofm#
  DB_NAME: PetApp
  DB_USER: postgres
  DB_PASSWORD: SolvusSoftware
  DB_HOST: localhost
  DB_PORT: 5432
  LOCAL_ALLOWED_HOST: 192.168.0.31
  AWS_ACCESS_KEY_ID: AKIAW6YLJIVHB3RCNIEO
  AWS_SECRET_ACCESS_KEY: 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
  AWS_DEFAULT_REGION: us-east-2
  AWS_STORAGE_BUCKET_NAME: petappfile

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # TODO: fix the testing folder here with how we do database setup
      # - name: Animal Model Test
      #   run: |
      #     python3 app/manage.py test app/animal/tests
