name: Django Automated Test Rerun

env:
  # Variables are set on Github Repo settings
  SECRET_KEY: $SECRET_KEY
  DB_NAME: $DB_NAME
  DB_USER: $DB_USER
  DB_PASSWORD: $DB_PASSWORD
  DB_HOST: $DB_HOST
  DB_PORT: $DB_PORT
  LOCAL_ALLOWED_HOST: $LOCAL_ALLOWED_HOST
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  AWS_STORAGE_BUCKET_NAME: $AWS_STORAGE_BUCKET_NAME

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # TODO: fix the testing folder here with how we do database setup
      # - name: Animal Model Test
      #   run: |
      #     python3 app/manage.py test app/animal/tests
