name: Django Automated Test Rerun

env:
  # Workflow level environment variables
  SECRET_KEY: $SECRET_KEY
  DB_NAME: $DB_NAME
  DB_USER: $DB_USER
  DB_PASSWORD: $DB_PASSWORD
  DB_HOST: postgres
  DB_PORT: $DB_PORT
  LOCAL_ALLOWED_HOST: $LOCAL_ALLOWED_HOST
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  AWS_STORAGE_BUCKET_NAME: $AWS_STORAGE_BUCKET_NAME

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-test-container-job:
    runs-on: ubuntu-latest
    container: python:3.10-bookworm
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_USER: $DB_USER
          POSTGRES_DB: $DB_NAME
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      - name: Check if running in a Continaer
        run: |
          if [[ "${{ runner.container }}" == "container" ]]; then
            echo "Running in a container"
          else
            echo "Running directly on the runner"
          fi
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Database Migration
        run: |
          python3 app/manage.py migrate
      
      # TODO: fix the testing folder here with how we do database setup
      # - name: Animal Model Test
      #   run: |
      #     python3 app/manage.py test app/animal/tests
